version: '3.1'

services:
  app:
    container_name: lacerta-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.docker.dev

    ports:
      - 4000:4000
    volumes:
      - ./_layouts:/usr/src/app/_layouts
      - ./_pages:/usr/src/app/_pages
      - ./_posts:/usr/src/app/_posts
      - ./frontend-interview:/usr/src/app/frontend-interview

