version: '3.1'

services:
  app:
    container_name: lacerta-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.docker.dev
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app/

